# Generated by Django 5.2.6 on 2025-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatmessage_timestamp_and_more'),
    ]

    operations = [
        # Delete all existing data before changing field type
        migrations.RunSQL(
            sql="TRUNCATE TABLE chatbot_chatmessage, chatbot_chatsession CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Drop and recreate the column as UUID
        migrations.RemoveField(
            model_name='chatsession',
            name='user_id',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_id',
            field=models.UUIDField(
                db_index=True, default='00000000-0000-0000-0000-000000000000'),
            preserve_default=False,
        ),
    ]
