# Generated by Django 5.2.6 on 2025-10-29 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(db_index=True)),
                ('changed_by_user_id', models.UUIDField()),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'appointment_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('vehicle_id', models.UUIDField(db_index=True)),
                ('assigned_employee_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('appointment_type', models.CharField(choices=[('maintenance', 'Regular Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('diagnostic', 'Diagnostic'), ('emergency', 'Emergency Service')], max_length=50)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('service_description', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by_user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-scheduled_date', '-scheduled_time'],
                'indexes': [models.Index(fields=['customer_id', 'scheduled_date'], name='appointment_custome_4293f6_idx'), models.Index(fields=['assigned_employee_id', 'scheduled_date'], name='appointment_assigne_cd43ea_idx'), models.Index(fields=['status', 'scheduled_date'], name='appointment_status_239f36_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('max_concurrent_appointments', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('date', 'start_time')},
            },
        ),
    ]
