# Generated by Django 4.2.7 on 2025-11-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Total time taken to complete the appointment in seconds (from TimeLog)'),
        ),
    ]
