# Generated by Django 5.2.6 on 2025-09-28 09:33

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the vehicle', primary_key=True, serialize=False)),
                ('make', models.CharField(help_text='Vehicle manufacturer (e.g., Toyota, BMW)', max_length=50)),
                ('model', models.CharField(help_text='Vehicle model (e.g., Camry, X5)', max_length=50)),
                ('year', models.IntegerField(help_text='Manufacturing year')),
                ('color', models.CharField(help_text='Vehicle color', max_length=30)),
                ('vin', models.CharField(help_text='Vehicle Identification Number (17 characters)', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='VIN must be exactly 17 characters and contain only valid characters', regex='^[A-HJ-NPR-Z0-9]{17}$')])),
                ('plate_number', models.CharField(help_text='Vehicle license plate number', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Plate number must be 2-10 characters with letters, numbers, hyphens, or spaces', regex='^[A-Z0-9\\-\\s]{2,10}$')])),
                ('customer_id', models.IntegerField(db_index=True, help_text='Reference to customer who owns this vehicle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is vehicle still in service')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id'], name='vehicles_custome_a752bc_idx'), models.Index(fields=['make', 'model'], name='vehicles_make_17021f_idx'), models.Index(fields=['year'], name='vehicles_year_fa878c_idx')],
            },
        ),
    ]
