# Generated by Django 4.2.7 on 2025-11-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='access_role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
    ]
