# Generated by Django 5.2.6 on 2025-09-27 09:39

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='Links to authentication service user ID', unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(default='', help_text='Complete address of the customer')),
                ('is_verified', models.BooleanField(default=False)),
                ('customer_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_service_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='customers_user_id_5b5af9_idx'), models.Index(fields=['email'], name='customers_email_92e882_idx'), models.Index(fields=['phone'], name='customers_phone_91048b_idx'), models.Index(fields=['last_name', 'first_name'], name='customers_last_na_89bb5f_idx')],
            },
        ),
    ]
