# Generated by Django 5.2.6 on 2025-11-01 15:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(db_index=True, help_text='Reference to employee from auth service')),
                ('shift_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Is shift currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['-shift_date', '-start_time'],
                'indexes': [models.Index(fields=['employee_id', 'shift_date'], name='shifts_employe_260916_idx'), models.Index(fields=['is_active'], name='shifts_is_acti_b80834_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(db_index=True, help_text='Reference to employee')),
                ('description', models.TextField(help_text='Task description')),
                ('vehicle', models.CharField(help_text='Vehicle being serviced', max_length=200)),
                ('service', models.CharField(help_text='Type of service', max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('inprogress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='inprogress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='timelogs.shift')),
            ],
            options={
                'db_table': 'time_logs',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['employee_id', '-start_time'], name='time_logs_employe_e3f382_idx'), models.Index(fields=['status'], name='time_logs_status_102143_idx'), models.Index(fields=['created_at'], name='time_logs_created_5894e2_idx')],
            },
        ),
    ]
