# Generated by Django 5.2.6 on 2025-11-04 10:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeTotal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(db_index=True, help_text='Reference to employee')),
                ('log_date', models.DateField(help_text='Date of the time logs')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked on this date', max_digits=5)),
                ('total_seconds', models.IntegerField(default=0, help_text='Total seconds worked on this date')),
                ('total_tasks', models.IntegerField(default=0, help_text='Total number of tasks/logs for this date')),
                ('project_tasks_count', models.IntegerField(default=0, help_text='Number of project tasks')),
                ('appointment_tasks_count', models.IntegerField(default=0, help_text='Number of appointment tasks')),
                ('project_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('appointment_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_time_totals',
                'ordering': ['-log_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ['-log_date', '-start_time']},
        ),
        migrations.RemoveIndex(
            model_name='timelog',
            name='time_logs_employe_e3f382_idx',
        ),
        migrations.AddField(
            model_name='timelog',
            name='appointment_id',
            field=models.CharField(blank=True, help_text='Reference to appointment if task_type is appointment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='log_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date of the log entry'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='project_id',
            field=models.CharField(blank=True, help_text='Reference to project if task_type is project', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='task_type',
            field=models.CharField(choices=[('project', 'Project Task'), ('appointment', 'Service Appointment')], default='appointment', help_text='Type of task', max_length=20),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='service',
            field=models.CharField(blank=True, help_text='Type of service', max_length=200),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='vehicle',
            field=models.CharField(blank=True, help_text='Vehicle being serviced', max_length=200),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['employee_id', '-log_date'], name='time_logs_employe_11242b_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['employee_id', 'log_date'], name='time_logs_employe_e74405_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['task_type'], name='time_logs_task_ty_47ec7d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytimetotal',
            index=models.Index(fields=['employee_id', '-log_date'], name='daily_time__employe_0a97df_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytimetotal',
            index=models.Index(fields=['log_date'], name='daily_time__log_dat_709f11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytimetotal',
            unique_together={('employee_id', 'log_date')},
        ),
    ]
