# Generated by Django 4.2.7 on 2025-11-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs', '0002_dailytimetotal_alter_timelog_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE daily_time_totals ALTER COLUMN employee_id TYPE uuid USING employee_id::text::uuid",
            reverse_sql="ALTER TABLE daily_time_totals ALTER COLUMN employee_id TYPE integer USING employee_id::text::integer"
        ),
        migrations.RunSQL(
            "ALTER TABLE time_logs ALTER COLUMN employee_id TYPE uuid USING employee_id::text::uuid",
            reverse_sql="ALTER TABLE time_logs ALTER COLUMN employee_id TYPE integer USING employee_id::text::integer"
        ),
    ]
