# Generated by Django 4.2.7 on 2025-11-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs', '0002_dailytimetotal_alter_timelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytimetotal',
            name='employee_id',
            field=models.UUIDField(db_index=True, help_text='Reference to employee'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='employee_id',
            field=models.UUIDField(db_index=True, help_text='Reference to employee'),
        ),
    ]
