# Generated by Django 4.2.7 on 2025-11-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs', '0003_alter_dailytimetotal_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='log_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date of the log entry', null=True),
        ),
    ]
