# Generated by Django 4.2.7 on 2025-11-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs', '0004_alter_timelog_log_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timelog',
            constraint=models.UniqueConstraint(condition=models.Q(('task_type', 'appointment'), models.Q(('status', 'completed'), _negated=True)), fields=('employee_id', 'task_type', 'appointment_id'), name='unique_active_appointment_log'),
        ),
        migrations.AddConstraint(
            model_name='timelog',
            constraint=models.UniqueConstraint(condition=models.Q(('task_type', 'project'), models.Q(('status', 'completed'), _negated=True)), fields=('employee_id', 'task_type', 'project_id'), name='unique_active_project_log'),
        ),
    ]
