# Generated by Django 5.2.6 on 2025-11-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelogs', '0005_add_unique_constraint_per_task'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timelog',
            name='unique_active_appointment_log',
        ),
        migrations.RemoveConstraint(
            model_name='timelog',
            name='unique_active_project_log',
        ),
    ]
