# Generated by Django 5.2.6 on 2025-09-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_user_id_5b5af9_idx',
            old_name='customers_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_email_92e882_idx',
            old_name='customers_email_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_phone_91048b_idx',
            old_name='customers_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_last_na_89bb5f_idx',
            old_name='customers_name_idx',
        ),
        migrations.RenameIndex(
            model_name='customerdocument',
            new_name='customer_do_custome_6923de_idx',
            old_name='documents_customer_idx',
        ),
        migrations.RenameIndex(
            model_name='customerdocument',
            new_name='customer_do_vehicle_e6b24c_idx',
            old_name='documents_vehicle_idx',
        ),
        migrations.RenameIndex(
            model_name='customerdocument',
            new_name='customer_do_documen_c93b4c_idx',
            old_name='documents_type_idx',
        ),
        migrations.RenameIndex(
            model_name='customernote',
            new_name='customer_no_custome_b06835_idx',
            old_name='notes_customer_idx',
        ),
        migrations.RenameIndex(
            model_name='customernote',
            new_name='customer_no_note_ty_218664_idx',
            old_name='notes_type_idx',
        ),
        migrations.RenameIndex(
            model_name='customernote',
            new_name='customer_no_is_impo_6c8a78_idx',
            old_name='notes_important_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='customer_ve_custome_9c996e_idx',
            old_name='vehicles_customer_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='customer_ve_vin_cbcd53_idx',
            old_name='vehicles_vin_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='customer_ve_license_2fe609_idx',
            old_name='vehicles_plate_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='customer_ve_make_2d845e_idx',
            old_name='vehicles_make_model_year_idx',
        ),
    ]
