# Generated by Django 5.2.6 on 2025-09-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customers_user_id_idx_customers_user_id_5b5af9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customernote',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerpreferences',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='apartment_unit',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='business_tax_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_business_customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='secondary_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default='', help_text='Complete address of the customer'),
        ),
        migrations.DeleteModel(
            name='CustomerDocument',
        ),
        migrations.DeleteModel(
            name='CustomerNote',
        ),
        migrations.DeleteModel(
            name='CustomerPreferences',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
