# Generated by Django 5.2.6 on 2025-10-17 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the project', primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(help_text='Customer ID from customer-service')),
                ('title', models.CharField(help_text='Title of the project', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the project')),
                ('expected_completion_date', models.DateField(help_text='Expected completion date of the project')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', help_text='Current status of the project', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='vehicles.vehicle')),
            ],
        ),
    ]
