# Generated by Django 5.2.6 on 2025-10-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Customer ID from customer-service', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', help_text='Current status of the project', max_length=20),
        ),
    ]
