# Generated by Django 5.2.6 on 2025-10-30 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_customer_id_alter_project_status'),
        ('vehicles', '0002_alter_customer_id_to_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer_id',
            field=models.UUIDField(db_index=True, help_text='Customer ID from customer-service'),
        ),
        migrations.AlterField(
            model_name='project',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='vehicles.vehicle'),
        ),
    ]
