# Generated by Django 5.2.6 on 2025-11-05 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_customer_id_alter_project_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status for the project', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_employee_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Employee ID assigned to this project from employee-service', null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the task', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the task', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the task')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', help_text='Current status of the task', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the task', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Due date for the task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
