# Generated by Django 5.2.6 on 2025-11-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_approval_status_project_assigned_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_employee_id',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_employee_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Employee ID assigned to this task from employee-service', null=True),
        ),
    ]
