# Generated by Django 5.2.6 on 2025-11-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_approval_status_project_assigned_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the task'),
        ),
    ]
