# Generated by Django 5.2.6 on 2025-11-07 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_assigned_employee_id_and_more'),
        ('projects', '0005_task_assigned_employee_id_alter_task_description'),
    ]

    operations = [
    ]
