# Generated by Django 5.2.6 on 2025-11-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_merge_20251107_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Total time taken to complete the task in seconds (from TimeLog)'),
        ),
    ]
