# Generated by Django 5.2.6 on 2025-10-18 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_user_id', models.IntegerField(db_index=True)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('SYSTEM', 'System Alert'), ('APPOINTMENT', 'Appointment Update'), ('VEHICLE', 'Vehicle Update'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
