# Generated by Django 5.2.6 on 2025-10-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_user_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
