# Generated by Django 5.2.6 on 2025-10-25 18:01

from django.db import migrations


def fix_admin_log_foreign_key(apps, schema_editor):
    """
    Fix the django_admin_log table to use UUID foreign key
    """
    with schema_editor.connection.cursor() as cursor:
        # First, clear any existing admin log entries to avoid FK conflicts
        cursor.execute("DELETE FROM django_admin_log")
        
        # Drop the foreign key constraint
        cursor.execute("""
            ALTER TABLE django_admin_log 
            DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_custom_user_id
        """)
        
        # Change the user_id column type to UUID
        cursor.execute("""
            ALTER TABLE django_admin_log 
            ALTER COLUMN user_id TYPE UUID USING user_id::text::uuid
        """)
        
        # Re-add the foreign key constraint
        cursor.execute("""
            ALTER TABLE django_admin_log 
            ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_custom_user_id 
            FOREIGN KEY (user_id) REFERENCES custom_user (id) DEFERRABLE INITIALLY DEFERRED
        """)


def reverse_admin_log_fix(apps, schema_editor):
    """
    Reverse the admin log fix (convert back to bigint)
    """
    with schema_editor.connection.cursor() as cursor:
        # Clear admin log entries
        cursor.execute("DELETE FROM django_admin_log")
        
        # Drop FK constraint
        cursor.execute("""
            ALTER TABLE django_admin_log 
            DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_custom_user_id
        """)
        
        # Change back to bigint
        cursor.execute("""
            ALTER TABLE django_admin_log 
            ALTER COLUMN user_id TYPE BIGINT
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_recreate_with_uuid'),
    ]

    operations = [
        migrations.RunPython(fix_admin_log_foreign_key, reverse_admin_log_fix),
    ]
