# Generated by Django 5.2.6 on 2025-10-25 18:02

from django.db import migrations


def fix_token_blacklist_foreign_key(apps, schema_editor):
    """
    Fix the token_blacklist_outstandingtoken table to use UUID foreign key
    """
    with schema_editor.connection.cursor() as cursor:
        # Clear existing tokens to avoid FK conflicts
        cursor.execute("DELETE FROM token_blacklist_outstandingtoken")
        cursor.execute("DELETE FROM token_blacklist_blacklistedtoken")
        
        # Drop the foreign key constraint
        cursor.execute("""
            ALTER TABLE token_blacklist_outstandingtoken 
            DROP CONSTRAINT IF EXISTS token_blacklist_outs_user_id_83bc629a_fk_custom_us
        """)
        
        # Change the user_id column type to UUID
        cursor.execute("""
            ALTER TABLE token_blacklist_outstandingtoken 
            ALTER COLUMN user_id TYPE UUID USING user_id::text::uuid
        """)
        
        # Re-add the foreign key constraint
        cursor.execute("""
            ALTER TABLE token_blacklist_outstandingtoken 
            ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_custom_us 
            FOREIGN KEY (user_id) REFERENCES custom_user (id) DEFERRABLE INITIALLY DEFERRED
        """)


def reverse_token_blacklist_fix(apps, schema_editor):
    """
    Reverse the token blacklist fix
    """
    with schema_editor.connection.cursor() as cursor:
        # Clear tokens
        cursor.execute("DELETE FROM token_blacklist_outstandingtoken")
        cursor.execute("DELETE FROM token_blacklist_blacklistedtoken")
        
        # Drop FK constraint
        cursor.execute("""
            ALTER TABLE token_blacklist_outstandingtoken 
            DROP CONSTRAINT IF EXISTS token_blacklist_outs_user_id_83bc629a_fk_custom_us
        """)
        
        # Change back to bigint
        cursor.execute("""
            ALTER TABLE token_blacklist_outstandingtoken 
            ALTER COLUMN user_id TYPE BIGINT
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fix_admin_log_foreign_key'),
    ]

    operations = [
        migrations.RunPython(fix_token_blacklist_foreign_key, reverse_token_blacklist_fix),
    ]
