# Generated by Django 5.2.6 on 2025-10-25 18:07

from django.db import migrations


def fix_user_groups_permissions_foreign_keys(apps, schema_editor):
    """
    Fix the custom_user_groups and custom_user_user_permissions tables to use UUID foreign keys
    """
    with schema_editor.connection.cursor() as cursor:
        # Clear existing data to avoid FK conflicts
        cursor.execute("DELETE FROM custom_user_groups")
        cursor.execute("DELETE FROM custom_user_user_permissions")
        
        # Fix custom_user_groups table
        print("Fixing custom_user_groups table...")
        
        # Drop foreign key constraints for groups table
        cursor.execute("""
            ALTER TABLE custom_user_groups 
            DROP CONSTRAINT IF EXISTS accounts_customuser__customuser_id_bc55088e_fk_accounts_
        """)
        
        # Change customuser_id column type to UUID
        cursor.execute("""
            ALTER TABLE custom_user_groups 
            ALTER COLUMN customuser_id TYPE UUID USING customuser_id::text::uuid
        """)
        
        # Re-add foreign key constraint
        cursor.execute("""
            ALTER TABLE custom_user_groups 
            ADD CONSTRAINT accounts_customuser__customuser_id_bc55088e_fk_accounts_ 
            FOREIGN KEY (customuser_id) REFERENCES custom_user (id) DEFERRABLE INITIALLY DEFERRED
        """)
        
        # Fix custom_user_user_permissions table
        print("Fixing custom_user_user_permissions table...")
        
        # Drop foreign key constraints for user permissions table
        cursor.execute("""
            ALTER TABLE custom_user_user_permissions 
            DROP CONSTRAINT IF EXISTS accounts_customuser__customuser_id_0deaefae_fk_accounts_
        """)
        
        # Change customuser_id column type to UUID
        cursor.execute("""
            ALTER TABLE custom_user_user_permissions 
            ALTER COLUMN customuser_id TYPE UUID USING customuser_id::text::uuid
        """)
        
        # Re-add foreign key constraint
        cursor.execute("""
            ALTER TABLE custom_user_user_permissions 
            ADD CONSTRAINT accounts_customuser__customuser_id_0deaefae_fk_accounts_ 
            FOREIGN KEY (customuser_id) REFERENCES custom_user (id) DEFERRABLE INITIALLY DEFERRED
        """)


def reverse_user_groups_permissions_fix(apps, schema_editor):
    """
    Reverse the user groups and permissions foreign key fixes
    """
    with schema_editor.connection.cursor() as cursor:
        # Clear data
        cursor.execute("DELETE FROM custom_user_groups")
        cursor.execute("DELETE FROM custom_user_user_permissions")
        
        # Revert groups table
        cursor.execute("""
            ALTER TABLE custom_user_groups 
            DROP CONSTRAINT IF EXISTS accounts_customuser__customuser_id_bc55088e_fk_accounts_
        """)
        cursor.execute("""
            ALTER TABLE custom_user_groups 
            ALTER COLUMN customuser_id TYPE BIGINT
        """)
        
        # Revert permissions table
        cursor.execute("""
            ALTER TABLE custom_user_user_permissions 
            DROP CONSTRAINT IF EXISTS accounts_customuser__customuser_id_0deaefae_fk_accounts_
        """)
        cursor.execute("""
            ALTER TABLE custom_user_user_permissions 
            ALTER COLUMN customuser_id TYPE BIGINT
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fix_token_blacklist_foreign_key'),
    ]

    operations = [
        migrations.RunPython(fix_user_groups_permissions_foreign_keys, reverse_user_groups_permissions_fix),
    ]
